### ISSUE TITLE
allow suppress of individual slots

### ISSUE THREAD

**Issue by mmckegg** [loopjs/loop-qwerty#5]
maybe repurpose "shift" and do Shift+Slotkey to mute?

Could make "space" used for "beat hold" instead of "shift" as currently.

**Comment by mmckegg** [comment]
With the new controls, might make more sense to enter delete mode using `0` on the number keys. Then any held would suppress

**Comment by janmonschke** [comment]
+1 for `0`

**Comment by mmckegg** [comment]
released in c5b87cd6b209d8228293ca798a25f9d667db439a / 3.4.0
